// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleAspMvcEF.Models;

public partial class Car
{
    public int CarId { get; set; }

    public string Model { get; set; }

    public string Type { get; set; }

    public double? BasePrice { get; set; }

    public string Color { get; set; }

    public int? Stock { get; set; }

    public virtual ICollection<DealerCar> DealerCars { get; set; } = new List<DealerCar>();

    public virtual ICollection<WarrantyRegistration> WarrantyRegistrations { get; set; } = new List<WarrantyRegistration>();
}