// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleAspMvcEF.Models;

public partial class ConsultHistory
{
    public int ConsultId { get; set; }

    public int CustomerId { get; set; }

    public int SalesPersonId { get; set; }

    public double? Budget { get; set; }

    public DateOnly? Date { get; set; }

    public string Note { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual SalesPerson SalesPerson { get; set; }
}