// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleAspMvcEF.Models;

public partial class Credit
{
    public int CreditId { get; set; }

    public int AgreementId { get; set; }

    public double CreditAmount { get; set; }

    public int? Tenor { get; set; }

    public double InterestRate { get; set; }

    public double MonthlyPaymentAmount { get; set; }

    public string CreditStatus { get; set; }

    public bool PaidFully { get; set; }

    public virtual Agreement Agreement { get; set; }
}