// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleAspMvcEF.Models;

public partial class Dealer
{
    public int DealerId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<DealerCar> DealerCars { get; set; } = new List<DealerCar>();

    public virtual ICollection<SalesPerson> SalesPeople { get; set; } = new List<SalesPerson>();
}