// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleAspMvcEF.Models;

public partial class PaymentHistory
{
    public int PaymentId { get; set; }

    public int AgreementId { get; set; }

    public double Amount { get; set; }

    public int? PaymentNumber { get; set; }

    public DateOnly? Date { get; set; }

    public virtual Agreement Agreement { get; set; }
}