// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleAspMvcEF.Models;

public partial class TestDrive
{
    public int TestDriveId { get; set; }

    public int CustomerId { get; set; }

    public int DealerCarId { get; set; }

    public int SalesPersonId { get; set; }

    public DateOnly? Date { get; set; }

    public string Feedback { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual DealerCar DealerCar { get; set; }

    public virtual SalesPerson SalesPerson { get; set; }
}