// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleAspMvcEF.Models;

public partial class WarrantyClaim
{
    public int ClaimId { get; set; }

    public int WarrantyId { get; set; }

    public string IssueReported { get; set; }

    public string ServiceCenter { get; set; }

    public DateOnly RepairDate { get; set; }

    public double RepairCost { get; set; }

    public string ClaimStatus { get; set; }

    public virtual WarrantyRegistration Warranty { get; set; }
}