// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleAspMvcEF.Models;

public partial class WarrantyRegistration
{
    public int WarrantyId { get; set; }

    public int CarId { get; set; }

    public int PurchaseId { get; set; }

    public int? WarrantyPeriodMonths { get; set; }

    public virtual Car Car { get; set; }

    public virtual Agreement Purchase { get; set; }

    public virtual ICollection<WarrantyClaim> WarrantyClaims { get; set; } = new List<WarrantyClaim>();
}