// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HandsOnLab.BO;

public partial class DealerCar
{
    public int DealerCarId { get; set; }

    public int CarId { get; set; }

    public int DealerId { get; set; }

    public double Price { get; set; }

    public int Stock { get; set; }

    public double? DiscountPercent { get; set; }

    public double? FeePercent { get; set; }

    public virtual Car Car { get; set; }

    public virtual Dealer Dealer { get; set; }

    public virtual ICollection<LetterOfIntent> LetterOfIntents { get; set; } = new List<LetterOfIntent>();

    public virtual ICollection<TestDrive> TestDrives { get; set; } = new List<TestDrive>();
}