// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HandsOnLab.BO;

public partial class LetterOfIntent
{
    public int LoiId { get; set; }

    public int DealerCarId { get; set; }

    public double? DiscountAmount { get; set; }

    public double? FeeAmount { get; set; }

    public double FinalPrice { get; set; }

    public double? DownPayment { get; set; }

    public string PaymentMethod { get; set; }

    public virtual Agreement Agreement { get; set; }

    public virtual DealerCar DealerCar { get; set; }
}