// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HandsOnLab.BO;

public partial class SalesPerson
{
    public int SalesId { get; set; }

    public string Name { get; set; }

    public int DealerId { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Agreement> Agreements { get; set; } = new List<Agreement>();

    public virtual ICollection<ConsultHistory> ConsultHistories { get; set; } = new List<ConsultHistory>();

    public virtual Dealer Dealer { get; set; }

    public virtual ICollection<TestDrive> TestDrives { get; set; } = new List<TestDrive>();
}